version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: opie2-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: opiedbuser
      POSTGRES_PASSWORD: opiepass
      POSTGRES_DB: opie2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: opie2-bot
    restart: unless-stopped
    env_file:
      - bot/.env
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: opie2-api
    restart: unless-stopped
    env_file:
      - api/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: opie2-web
    restart: unless-stopped
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres-data:
