services:
  postgres:
    image: postgres:14
    container_name: opie2-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: opie2-chroma
    restart: unless-stopped
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - "8713:8000"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: opie2-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - chroma

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: opie2-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - chroma

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: opie2-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api
